name: h-microkernel-ci-cd
run-name: ${{ github.actor }} testing on push
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Build
        shell: bash
        run: gcc h-microkernel.c -o h-microkernel.exe

      - name: Deploy
        run: ./microkernel.exe
