name: ci-cd

run-name: ${{ github.actor }} testing on push

on: [push]

jobs:

  # Name of the Job
  build_and_run:
  
    # Runner
    runs-on: ubuntu-latest
    
    # Groups all the steps that run in "build-and-run" job
    steps:
      
      # Action - Checks out repository onto the runner 
      - uses: actions/checkout@v4

      # Shell - Compile
      - name: Build
        shell: bash
        run: gcc h-microkernel.c -o h-microkernel.exe

      # Shell - Run
      - name: Deploy
        run: ./h-microkernel.exe
